/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CountrySelector: typeof import('./components/atoms/CountrySelector.vue')['default']
    ForecastList: typeof import('./components/organisms/ForecastList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadingSpinner: typeof import('./components/atoms/LoadingSpinner.vue')['default']
    PhoneNumberInput: typeof import('./components/atoms/PhoneNumberInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/molecules/SearchBar.vue')['default']
    TemperatureDisplay: typeof import('./components/atoms/TemperatureDisplay.vue')['default']
    ThemeToggle: typeof import('./components/atoms/ThemeToggle.vue')['default']
    WeatherCard: typeof import('./components/molecules/WeatherCard.vue')['default']
    WeatherIcon: typeof import('./components/atoms/WeatherIcon.vue')['default']
    WeatherPageTemplate: typeof import('./components/templates/WeatherPageTemplate.vue')['default']
  }
}
